service: scinapse-feedback

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  region: us-east-1
  environment:
    SLACK_SCINAPSE_FEEDBACK_WEBHOOK_URL: ${env:SLACK_SCINAPSE_FEEDBACK_WEBHOOK_URL}
    GOOGLE_SHEET_CLIENT_EMAIL: ${env:GOOGLE_SHEET_CLIENT_EMAIL}
    GOOGLE_SHEET_PRIVATE_KEY: ${env:GOOGLE_SHEET_PRIVATE_KEY}

functions:
  handleFeedback:
    handler: handler.handleFeedback
    events:
      - http:
          path: feedbacks/new
          method: post
