service: scinapse-feedback

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  region: us-east-1
  environment:
    SLACK_TOKEN: ${env:SLACK_TOKEN}

functions:
  handleFeedback:
    handler: handler.handleFeedback
    events:
      - http:
          path: feedbacks/new
          method: post
