service: scinapse-feedback

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
#  stage: dev
#  region: us-east-1

functions:
  handleFeedback:
    handler: handler.handleFeedback
